name: Machinekit
highlighter: rouge
relative_permalinks: false
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
repository: https://github.com/machinekit/machinekit

gems:
  - jekyll-asciidoc
  - asciidoctor-diagram
  - jekyll-sitemap

asciidoc: asciidoctor
asciidoc_ext: asciidoc,ad

asciidoctor:
  safe: 0
  attributes:
    - hardbreaks!

defaults:
  -
    scope:
      path: ""
    values:
      edit-repo: "https://github.com/mhaberler/machinekit-docs/"
      edit-branch: "clean-jekyll-1"
  -
    scope:
# applies to all files under:
      path: "docs"
    values:
      layout: "docs"
      docs-dir: "docs"


# stage manpage sources here for comparison
exclude:  [staging scripts]

# Google services - preview.machinekit.io
google_analytics:   UA-48383649-2

# for www.machinekit.io - activate on switch!
#google_analytics:  UA-48383649-1
